# You are assigned a task to restart a number of servers in a particular sequence.
# The sequence and the commands to be used are given below. Remember the commands should be run on respective servers only.
# Refer to the inventory file and update the playbook to create the below sequence.
# Note: Use the description below to name the plays and tasks
# Warning: Do not use this playbook in a real setup. There are better ways to do these actions. This is only for simple practise.
# ------------------------------------------------------------------
# 1. Stop the web services on web server nodes - service httpd stop
# 2. Shutdown the database services on db server nodes - service mysql stop
# 3. Restart all servers (web and db) at once - /sbin/shutdown -r
# 4. Start the database services on db server nodes - service mysql start
# 5. Start the web services on web server nodes - service httpd start
# --------------------------------------------------------
# Refer to the attached inventory.txt file.

# BEFORE
# ---------------

# AFTER
# ---------------

-
  name: Stop the web services on web server nodes
  hosts: web_nodes
  tasks:
    -
      name: Stop the web services on web server nodes
      command: service httpd stop

-
  name: Shutdown the database services on db server nodes
  hosts: db_nodes
  tasks:
    -
      name: Shutdown the database services on db server nodes
      command: service mysql stop

-
  name: Restart all servers (web and db) at once
  hosts: all_nodes
  tasks:
    -
      name: Restart all servers (web and db) at once
      command: /sbin/shutdown -r

-
  name: Start the database services on db server nodes
  hosts: db_nodes
  tasks:
    -
      name: Start the database services on db server nodes
      command: service mysql start

-
  name: Start the web services on web server nodes
  hosts: web_nodes
  tasks:
    -
      name: Start the web services on web server nodes
      command: service httpd start