# Update the playbook with a play to "Execute a script on all web server nodes". The script is located at /tmp/install_script.sh

# ------------------------------
#           BEFORE
# ------------------------------

# ------------------------------
#           AFTER
# ------------------------------
-
  name: Execute a script on all web server nodes
  hosts: web_nodes
  tasks:
    -
      name: Execute a script on all web server nodes
      script: /tmp/install_script.sh
