# Update the playbook to add a new task in the beginning to add an entry into /etc/resolv.conf file for hosts. The line to be added is 'nameserver 10.1.250.10'
# Note the new task must be executed first, so place it accordingly.
# lineinfile documentation

# BEFORE
# ---------------
#-
#  name: Execute a script on all web server nodes and start httpd service
#  hosts: web_nodes
#  tasks:
#    -
#      name: Execute a script
#      script: /tmp/install_script.sh
#
#    -
#      name: Start httpd service
#      service:
#        name: httpd
#        state: present
#
#

# AFTER
# ---------------
-
  name: Execute a script on all web server nodes and start httpd service
  hosts: web_nodes
  tasks:
    -
      name: Update entry into /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.1.250.10'

    -
      name: Execute a script
      script: /tmp/install_script.sh

    -
      name: Start httpd service
      service:
        name: httpd
        state: present
